#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                      - Movement by Rotation -                                      *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses the Shaft Encoders to move forward for a certain distance.                      *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Changing the value of 'distance' will change how far your robot will travel.                *|
|*        !! 360 is equal to one full rotation of the axel !!                                         *|
|*    3)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Quadrature enc.   Right side encoder                *|
|*    Digital - Port 3,4  leftEncoder         VEX Quadrature enc.   Left side encoder                 *|
\*-----------------------------------------------------------------------------------------------4246-*/
int power = 63;

int radius = 5;
int ummal = 2 * PI * radius;
int length = 360 * (50 / ummal);
int counter = 1;

void forward(int length){
	SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder] = 0;
	while(abs(SensorValue[leftEncoder]) < length)
	{
		motor[rightMotor] = power;
		motor[leftMotor]  = power;
	}
	motor[rightMotor] = 0;
	motor[leftMotor] = 0;
}

void turnLeft () {
		SensorValue[rightEncoder] = 0;
		SensorValue[leftEncoder] = 0;

		// While the encoders have not yet met their goal: (left is compared negativly since it will in reverse)
	  while(SensorValue[rightEncoder] < (-1 * r * rotations) && SensorValue[leftEncoder] > (r * rotations))
	  {
	    motor[rightMotor] = 63;         // Run the right motor forward at half speed
	    motor[leftMotor]  = -63;        // Run the left motor backward at half speed
	  }
	  motor[rightMotor] = 0;            /* Stop both motors!  This is important so that each function          */
	  motor[leftMotor]  = 0;            /* can act independantly as a "chunk" of code, without any loose ends. */

}

void turnRight () {
		SensorValue[rightEncoder] = 0;
		SensorValue[leftEncoder] = 0;

			// While the encoders have not yet met their goal: (left is compared negativly since it will in reverse)
	  while(SensorValue[rightEncoder] < (r * rotations) && SensorValue[leftEncoder] > (-1 * r * rotations))
	  {
	    motor[rightMotor] = 63;         // Run the right motor forward at half speed
	    motor[leftMotor]  = -63;        // Run the left motor backward at half speed
	  }
	  motor[rightMotor] = 0;            /* Stop both motors!  This is important so that each function          */
	  motor[leftMotor]  = 0;            /* can act independantly as a "chunk" of code, without any loose ends. */
}


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  wait1Msec(2000);                  // Wait 2000 milliseconds before continuing.

  for(; counter <= 4; counter++){
	  forward(length);
	  wait1Msec(1000);
	}

  motor[rightMotor] = 0;            /* Stop the motors once desired */
  motor[leftMotor]  = 0;            /* distance has been reached.   */
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
